version: '3'

services:
    fly:
        build:
            context: ./fly
            args:
                FLY_CLI_VERSION: ${FLY_CLI_VERSION}
        environment:
            CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
            CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASIC_AUTH_USERNAME}
            CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASIC_AUTH_PASSWORD}
        image: localhost/fly
        tty: true

    concourse-db:
        image: postgres:9.6
        environment:
            POSTGRES_DB: "${CONCOURSE_POSTGRES_DATABASE}"
            POSTGRES_USER: "${CONCOURSE_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${CONCOURSE_POSTGRES_PASSWORD}"
            PGDATA: /database
        volumes:
            - ./pgdata:/database:rw

    concourse-web:
        image: concourse/concourse
        links: [concourse-db]
        command: web
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        volumes: ["./keys/web:/concourse-keys"]
        restart: unless-stopped # required so that it retries until concourse-db comes up
        environment:
            CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASIC_AUTH_USERNAME}
            CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASIC_AUTH_PASSWORD}
            CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
            CONCOURSE_POSTGRES_HOST: concourse-db
            CONCOURSE_POSTGRES_USER: "${CONCOURSE_POSTGRES_USER}"
            CONCOURSE_POSTGRES_PASSWORD: "${CONCOURSE_POSTGRES_PASSWORD}"
            CONCOURSE_POSTGRES_DATABASE: "${CONCOURSE_POSTGRES_DATABASE}"

    concourse-worker-1:
        image: concourse/concourse
        privileged: true
        links: [concourse-web]
        depends_on: [concourse-web]
        command: worker
        volumes: ["./keys/worker:/concourse-keys"]
        environment:
            CONCOURSE_TSA_HOST: concourse-web

    concourse-worker-2:
        image: concourse/concourse
        privileged: true
        links: [concourse-web]
        depends_on: [concourse-web]
        command: worker
        volumes: ["./keys/worker:/concourse-keys"]
        environment:
            CONCOURSE_TSA_HOST: concourse-web
